version: "2"

services:
  client:
    image: node:latest
    command: yarn start
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
